# Docker Registry â€” pull-through cache for Docker Hub (registry-1.docker.io)
# Docs: https://distribution.github.io/distribution/recipes/mirror/

version: 0.1

storage:
  filesystem:
    rootdirectory: /var/lib/registry

proxy:
  remoteurl: https://registry-1.docker.io

http:
  addr: 0.0.0.0:5000
