# Docker Registry â€” pull-through cache for Microsoft Container Registry (mcr.microsoft.com)
# Docs: https://distribution.github.io/distribution/recipes/mirror/

version: 0.1

storage:
  filesystem:
    rootdirectory: /var/lib/registry

proxy:
  remoteurl: https://mcr.microsoft.com

http:
  addr: 0.0.0.0:5000
